// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL03_TMvQOGPGp4XdPN45Vj3ut_j--Yzw',
    appId: '1:302917996812:web:45423f64833a1c36f33929',
    messagingSenderId: '302917996812',
    projectId: 'my-app-a0341',
    authDomain: 'my-app-a0341.firebaseapp.com',
    databaseURL: 'https://my-app-a0341-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-a0341.appspot.com',
    measurementId: 'G-Q1LNM0NRD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUggTT8CPqeNnt22ez7XZX126hFx-JctE',
    appId: '1:302917996812:android:1d7dd38fd9990d22f33929',
    messagingSenderId: '302917996812',
    projectId: 'my-app-a0341',
    databaseURL: 'https://my-app-a0341-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-a0341.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EqHrNG-PjUBw8Wr-zsxE7XEs9BTiArs',
    appId: '1:302917996812:ios:8895f5a63237ab53f33929',
    messagingSenderId: '302917996812',
    projectId: 'my-app-a0341',
    databaseURL: 'https://my-app-a0341-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-a0341.appspot.com',
    iosBundleId: 'com.example.theapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9EqHrNG-PjUBw8Wr-zsxE7XEs9BTiArs',
    appId: '1:302917996812:ios:8895f5a63237ab53f33929',
    messagingSenderId: '302917996812',
    projectId: 'my-app-a0341',
    databaseURL: 'https://my-app-a0341-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-a0341.appspot.com',
    iosBundleId: 'com.example.theapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL03_TMvQOGPGp4XdPN45Vj3ut_j--Yzw',
    appId: '1:302917996812:web:1d2dc2f452337f35f33929',
    messagingSenderId: '302917996812',
    projectId: 'my-app-a0341',
    authDomain: 'my-app-a0341.firebaseapp.com',
    databaseURL: 'https://my-app-a0341-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-a0341.appspot.com',
    measurementId: 'G-BEH5CEB7JX',
  );
}
